### ISSUE TITLE
error: Symfony\Component\Process\Process::fromShellCommandline(): Argument #1 ($command) must be of type string, null given, called in /opt/pimcore/vendor/cors/workflow-gui/src/WorkflowGUI/Controller/WorkflowController.php on line 345

### ISSUE THREAD

**Issue by ismetsener** [cors-gmbh/pimcore-workflow-gui#1]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Branch?          | 2.0.1

I get an error when I make a workflow, 
* Settings/Workflows
* in workflow tab "visualiazation" I get this error:

Symfony\Component\Process\Process::fromShellCommandline(): Argument #1 ($command) must be of type string, null given, called in /opt/pimcore/vendor/cors/workflow-gui/src/WorkflowGUI/Controller/WorkflowController.php on line 345

how can we solve this?

with kind regards,
Ismet

**Comment by dpfaffenbauer** [comment]
we just had that too and solved it now
